/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__heb8d74e0fd495306: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h47cdbd6bdf6859a0: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h294459a441a00547: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h5337e60e5c25d8bc: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc481aa28d127b830: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hec80bf4ceeb4a63b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__he47ba46bd205a573: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__h62ac486f1ae980e8: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
